# Generated by Django 6.0.3 on 2026-03-30 02:27

import django.db.models.deletion
import doc_tecnicos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganismoNorma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('IEC', 'IEC - International Electrotechnical Commission'), ('IEEE', 'IEEE - Institute of Electrical and Electronics Engineers'), ('NBR', 'NBR - Norma Brasileira'), ('CIGRE', 'CIGRE - Conseil International des Grands Réseaux Électriques'), ('ASTM', 'ASTM - American Society for Testing and Materials'), ('ASCE', 'ASCE - American Society of Civil Engineers'), ('NB', 'NB - Norma Boliviana')], max_length=10, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Organismo de norma',
                'verbose_name_plural': 'Organismos de normas',
            },
        ),
        migrations.CreateModel(
            name='DocumentoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('anio', models.IntegerField()),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(upload_to='doc_tecnicos/', validators=[doc_tecnicos.models.validar_extension_pdf])),
                ('organismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='doc_tecnicos.organismonorma')),
            ],
            options={
                'verbose_name': 'Documento técnico',
                'verbose_name_plural': 'Documentos técnicos',
            },
        ),
    ]
