# Generated by Django 6.0.3 on 2026-03-30 03:12

import doc_tecnicos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroIngElectrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('autor', models.CharField(max_length=200)),
                ('anio', models.IntegerField()),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(upload_to='libros_ing/', validators=[doc_tecnicos.models.validar_extension_pdf])),
            ],
            options={
                'verbose_name': 'Libro Ing. Eléctrica',
                'verbose_name_plural': 'Libros Ing. Eléctrica',
            },
        ),
        migrations.AlterModelOptions(
            name='documentotecnico',
            options={'verbose_name': 'Artículo técnico', 'verbose_name_plural': 'Artículos técnicos'},
        ),
        migrations.AlterModelOptions(
            name='organismonorma',
            options={'verbose_name': 'Norma', 'verbose_name_plural': 'Normas'},
        ),
    ]
