# Generated by Django 6.0.3 on 2026-03-30 03:44

import doc_tecnicos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_tecnicos', '0003_categoria_documentotecnico_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='recomendacion',
            field=models.IntegerField(default=5, validators=[doc_tecnicos.models.validar_recomendacion]),
        ),
        migrations.AddField(
            model_name='documentotecnico',
            name='recomendacion',
            field=models.IntegerField(default=5, validators=[doc_tecnicos.models.validar_recomendacion]),
        ),
        migrations.AddField(
            model_name='libroingelectrica',
            name='recomendacion',
            field=models.IntegerField(default=5, validators=[doc_tecnicos.models.validar_recomendacion]),
        ),
        migrations.AddField(
            model_name='organismonorma',
            name='recomendacion',
            field=models.IntegerField(default=5, validators=[doc_tecnicos.models.validar_recomendacion]),
        ),
    ]
