# Generated by Django 6.0.3 on 2026-03-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_tecnicos', '0004_categoria_recomendacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='paginas',
            field=models.IntegerField(default=0, help_text='Número de hojas'),
        ),
        migrations.AddField(
            model_name='documentotecnico',
            name='paginas',
            field=models.IntegerField(default=0, help_text='Número de hojas'),
        ),
        migrations.AddField(
            model_name='libroingelectrica',
            name='paginas',
            field=models.IntegerField(default=0, help_text='Número de hojas'),
        ),
        migrations.AddField(
            model_name='organismonorma',
            name='paginas',
            field=models.IntegerField(default=0, help_text='Número de hojas'),
        ),
    ]
