# Generated by Django 6.0.3 on 2026-03-31 02:17

import django.utils.timezone
import doc_tecnicos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_tecnicos', '0005_categoria_paginas_documentotecnico_paginas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentotecnico',
            options={'permissions': [('ver_reporte_documentos', 'Ver reporte de documentos'), ('descargar_documento', 'Descargar documento técnico')], 'verbose_name': 'Artículo técnico', 'verbose_name_plural': 'Artículos técnicos'},
        ),
        migrations.AddField(
            model_name='documentotecnico',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentotecnico',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='libroingelectrica',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libroingelectrica',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='documentotecnico',
            name='anio',
            field=models.IntegerField(validators=[doc_tecnicos.validators.validar_anio]),
        ),
        migrations.AlterField(
            model_name='libroingelectrica',
            name='anio',
            field=models.IntegerField(validators=[doc_tecnicos.validators.validar_anio]),
        ),
    ]
