# Generated by Django 6.0.3 on 2026-03-31 02:39

import doc_tecnicos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_tecnicos', '0006_alter_documentotecnico_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organismonorma',
            name='nombre',
        ),
        migrations.AddField(
            model_name='organismonorma',
            name='anio',
            field=models.IntegerField(blank=True, null=True, validators=[doc_tecnicos.validators.validar_anio], verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='organismonorma',
            name='codigo',
            field=models.CharField(blank=True, help_text='Ej: IEC-60076', max_length=100, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='organismonorma',
            name='denominacion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Denominación'),
        ),
        migrations.AddField(
            model_name='organismonorma',
            name='norma',
            field=models.CharField(choices=[('IEC', 'IEC - International Electrotechnical Commission'), ('IEEE', 'IEEE - Institute of Electrical and Electronics Engineers'), ('NBR', 'NBR - Norma Brasileira'), ('CIGRE', 'CIGRE - Conseil International des Grands Réseaux Électriques'), ('ASTM', 'ASTM - American Society for Testing and Materials'), ('ASCE', 'ASCE - American Society of Civil Engineers'), ('NB', 'NB - Norma Boliviana')], default='IEC', max_length=10, unique=True, verbose_name='Norma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organismonorma',
            name='texto',
            field=models.TextField(blank=True, verbose_name='Texto/Resumen'),
        ),
    ]
