# Generated by Django 6.0.3 on 2026-03-30 02:27

import django.db.models.deletion
import libros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/', validators=[libros.models.validar_extension_portada]),
        ),
        migrations.CreateModel(
            name='ArchivoLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pdf', 'PDF'), ('epub', 'EPUB'), ('metadatos', 'Metadatos EPUB')], max_length=20)),
                ('archivo', models.FileField(upload_to='archivos/', validators=[libros.models.validar_extension_archivo])),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='libros.libro')),
            ],
            options={
                'verbose_name_plural': 'Archivos de libros',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('novela', 'Novela'), ('matematicas', 'Matemáticas'), ('fisica', 'Física'), ('quimica', 'Química'), ('ajedrez', 'Ajedrez'), ('ing_electrica', 'Ingeniería Eléctrica')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgeneros', to='libros.genero')),
            ],
            options={
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.AddField(
            model_name='libro',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libros', to='libros.genero'),
        ),
        migrations.DeleteModel(
            name='Archivo',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
