# Generated by Django 6.0.3 on 2026-03-30 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_remove_libro_categoria_alter_libro_portada_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivolibro',
            options={'verbose_name': 'Tipo Formato', 'verbose_name_plural': 'Tipo Formato'},
        ),
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autor'},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name': 'Género', 'verbose_name_plural': 'Género'},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name': 'Subgénero', 'verbose_name_plural': 'Subgénero'},
        ),
    ]
