# Generated by Django 6.0.3 on 2026-03-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_categoria_libro_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name': 'Género', 'verbose_name_plural': 'Géneros'},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.AlterField(
            model_name='genero',
            name='tipo',
            field=models.CharField(choices=[('novela', 'Novela'), ('matematicas', 'Matemáticas'), ('fisica', 'Física'), ('quimica', 'Química'), ('ajedrez', 'Ajedrez'), ('ing_electrica', 'Ingeniería Eléctrica'), ('politica', 'Política'), ('historia', 'Historia'), ('ciencia', 'Ciencia'), ('otros', 'Otros')], max_length=50),
        ),
    ]
