# Generated by Django 6.0.3 on 2026-03-30 03:44

import libros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0005_alter_genero_options_alter_libro_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivolibro',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='archivolibro',
            name='recomendacion',
            field=models.IntegerField(default=5, validators=[libros.models.validar_recomendacion]),
        ),
        migrations.AddField(
            model_name='autor',
            name='recomendacion',
            field=models.IntegerField(default=5, validators=[libros.models.validar_recomendacion]),
        ),
        migrations.AddField(
            model_name='categoria',
            name='recomendacion',
            field=models.IntegerField(default=5, validators=[libros.models.validar_recomendacion]),
        ),
        migrations.AddField(
            model_name='genero',
            name='recomendacion',
            field=models.IntegerField(default=5, validators=[libros.models.validar_recomendacion]),
        ),
        migrations.AddField(
            model_name='libro',
            name='recomendacion',
            field=models.IntegerField(default=5, validators=[libros.models.validar_recomendacion]),
        ),
    ]
