# Generated by Django 6.0.3 on 2026-03-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0006_archivolibro_descripcion_archivolibro_recomendacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivolibro',
            name='paginas',
            field=models.IntegerField(default=0, help_text='Número de hojas'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='paginas',
            field=models.IntegerField(default=0, help_text='Número de hojas'),
        ),
        migrations.AddField(
            model_name='genero',
            name='paginas',
            field=models.IntegerField(default=0, help_text='Número de hojas'),
        ),
        migrations.AddField(
            model_name='libro',
            name='paginas',
            field=models.IntegerField(default=0, help_text='Número de hojas'),
        ),
    ]
