# Generated by Django 6.0.3 on 2026-03-31 02:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0007_archivolibro_paginas_categoria_paginas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'permissions': [('ver_reporte_libros', 'Ver reporte de libros')], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'permissions': [('descargar_libro', 'Descargar libro')], 'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.AddField(
            model_name='archivolibro',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archivolibro',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='archivolibro',
            name='tipo',
            field=models.CharField(choices=[('pdf', 'PDF'), ('epub', 'EPUB'), ('metadatos', 'Metadatos EPUB')], default='pdf', max_length=20),
        ),
        migrations.AlterField(
            model_name='genero',
            name='tipo',
            field=models.CharField(choices=[('novela', 'Novela'), ('matematicas', 'Matemáticas'), ('fisica', 'Física'), ('quimica', 'Química'), ('ajedrez', 'Ajedrez'), ('ing_electrica', 'Ingeniería Eléctrica'), ('politica', 'Política'), ('historia', 'Historia'), ('ciencia', 'Ciencia'), ('otros', 'Otros')], default='otros', max_length=50),
        ),
    ]
